name: ci

on: [ push, pull_request ]

jobs:
 test:
  name: ${{ matrix.config.image-slug }}
  runs-on: ubuntu-latest
  strategy:
   matrix:
    config:
    - { docker-file: 'Dockerfile.cpu', image-slug: 'facefusion/facefusion:${{ github.ref_name }}-cpu' }
    - { docker-file: 'Dockerfile.cuda', image-slug: 'facefusion/facefusion:${{ github.ref_name }}-cuda' }
    - { docker-file: 'Dockerfile.tensorrt', image-slug: 'facefusion/facefusion:${{ github.ref_name }}-tensorrt' }
    - { docker-file: 'Dockerfile.rocm', image-slug: 'facefusion/facefusion:${{ github.ref_name }}-rocm' }
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Build
    run: docker build -f ${{ matrix.config.docker-file }} -t ${{ matrix.config.image-slug }} .
  - name: Run
    run: docker run -d ${{ matrix.config.image-slug }}
  - name: Validate
    run: docker ps | grep -q ${{ matrix.config.image-slug }}
 deploy:
  name: ${{ matrix.config.image-slug }}
  runs-on: ubuntu-latest
  needs: test
  strategy:
   matrix:
    config:
    - { docker-file: 'Dockerfile.cpu', image-slug: 'facefusion/facefusion:${{ github.ref_name }}-cpu' }
    - { docker-file: 'Dockerfile.cuda', image-slug: 'facefusion/facefusion:${{ github.ref_name }}-cuda' }
    - { docker-file: 'Dockerfile.tensorrt', image-slug: 'facefusion/facefusion:${{ github.ref_name }}-tensorrt' }
    - { docker-file: 'Dockerfile.rocm', image-slug: 'facefusion/facefusion:${{ github.ref_name }}-rocm' }
  steps:
  - name: Login
    uses: docker/login-action@v2
    with:
     username: ${{ secrets.DOCKER_USERNAME }}
     password: ${{ secrets.DOCKER_PASSWORD }}
  - name: Checkout
    uses: actions/checkout@v2
  - name: Build
    run: docker build -f ${{ matrix.config.docker-file }} -t ${{ matrix.config.image-slug }} .
  - name: Deploy
    run: docker push ${{ matrix.config.image-slug }}
  - name: Logout
    run: docker logout
